# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "kmaster"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |v|
    v.memory = 5120  # 5 GB RAM for master node
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
  cat <<EOF > /home/vagrant/first_steps.sh
#!/bin/bash

ssh -V

sudo systemctl enable ssh
sudo systemctl start ssh

sudo systemctl status ssh

sudo adduser alice # set alice's password to "bubblegum"

sudo usermod -aG sudo alice # add alice to sudoers

sudo rm /etc/ssh/sshd_config

sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf' # temporarily use Google's DNS

sudo curl -L "https://raw.githubusercontent.com/ForestMint/minimal_SSH_config/refs/heads/master/ssh_config_file_to_download" -o /etc/ssh/sshd_config

sudo reboot

EOF

  chmod +x /home/vagrant/first_steps.sh
SHELL











  config.vm.provision "shell", inline: <<-SHELL
  cat <<EOF > /home/vagrant/install_docker.sh
#!/bin/bash

sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf' # temporarily use Google's DNS

sudo apt update
sudo apt install docker.io -y
docker --version
systemctl status docker

EOF

  chmod +x /home/vagrant/install_docker.sh
SHELL










  config.vm.provision "shell", inline: <<-SHELL
  cat <<EOF > /home/vagrant/install_K8s_suite.sh
#!/bin/bash

sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf' # temporarily use Google's DNS

# Update and install dependencies

sudo apt update
sudo apt install -y apt-transport-https ca-certificates curl gpg

# Add the Kubernetes GPG key

sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# Add the Kubernetes APT repository

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

# Update package lists

sudo apt update

# Install kubeadm (and optionally and kubelet)

sudo apt install -y kubeadm kubelet kubernetes-cni

# Prevent automatic updates (optional but recommended)

sudo apt-mark hold kubeadm kubelet

# Verify installation

kubeadm version
kubelet --version
dpkg -l | grep kubernetes-cni


EOF

  chmod +x /home/vagrant/install_K8s_suite.sh
SHELL

end


