# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
  cat <<EOF > /home/vagrant/first_steps.sh
#!/bin/bash

ssh -V

sudo systemctl enable ssh
sudo systemctl start ssh

sudo systemctl status ssh

sudo adduser alice # set alice's password to "bubblegum"

sudo usermod -aG sudo alice # add alice to sudoers

sudo rm /etc/ssh/sshd_config

sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf' # temporarily use Google's DNS

sudo curl -L "https://raw.githubusercontent.com/ForestMint/get_started_with_K8s/refs/heads/feat/run_with_arch_linux/ssh_congig_template" -o /etc/ssh/sshd_config

sudo reboot

EOF

  chmod +x /home/vagrant/first_steps.sh
SHELL

end


